# Generated by Django 4.0.4 on 2022-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=200)),
                ('release', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=120)),
                ('ip_address', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('username', 'mac_address')},
            },
        ),
    ]
