# Generated by Django 4.0.4 on 2022-07-29 16:58

from django.db import migrations


class Migration(migrations.Migration):
    """Migration class in 0002"""

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
